[View in Colaboratory](https://colab.research.google.com/github/gopal2812/mlblr/blob/master/deeplearningcalculationforupdatingbias.ipynb)

In [51]:
import random
for x in range(19):
  print(round(random.random(),2))

0.03
0.81
0.78
0.45
1.0
0.68
0.07
0.96
0.19
0.38
0.7
0.54
0.73
0.07
0.11
0.68
0.88
0.16
0.19


In [86]:
import numpy as np
import tensorflow as tf
sess = tf.InteractiveSession()

print("Step 1: Initialize weights and biases with random values")
#(There are methods to initialize weights and biases but for now initialize with random values)
x=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
wh=np.array([[0.49,0.69,0.47],[0.38,0.85,0.98],[0.02,0.91,0.05],[0.93, 0.31,0.07]])
bh=np.array([[0.69,0.86,0.94],[0.69,0.86,0.94],[0.69,0.86,0.94]])
w_out=np.array([0.98,0.39,0.98])
b_out=np.array([0.91, 0.91, 0.91])
print(x)
print(wh)
print(bh)
print(w_out)
print(b_out)


print("Step 2 Calculate hidden layer input:")
hidden_layer_input= x.dot(w) +b
print(hidden_layer_input)

print("Step 3: Perform non-linear transformation on hidden linear input")
#hiddenlayer_activations = sigmoid(hidden_layer_input)
y = tf.sigmoid(hidden_layer_input)
hiddenlayer_activations = y.eval()
print(hiddenlayer_activations)

print("Step 4: Perform linear and non-linear transformation of hidden layer activation at output layer")
w_op= np.dot(u,w_out) +b_out
w_act=tf.sigmoid(w_op)
output=w_act.eval()
print(output)

print("Step 5: Calculate gradient of Error(E) at output layer")
#E = y-output
y=[1,1,0]
E=y-output
print(y-output)

def sigmoid_grad(x):
   ex = np.exp(-x)
   y = ex / (1 + ex)**2
   return y
  
print("Step 6: Compute slope at output and hidden layer")
#Slope_output_layer= derivatives_sigmoid(output)
#Slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
slope_output_layer= sigmoid_grad(output)
slope_hidden_layer = sigmoid_grad(hiddenlayer_activations)
print(slope_output_layer)
print(slope_hidden_layer)

print("Step 7: Compute delta at output layer")
#d_output = E * slope_output_layer*lr
d_output = E * slope_output_layer*0.1
print(d_output)

print("Step 8: Calculate Error at hidden layer")
#Error_at_hidden_layer = matrix_dot_product(d_output, wout.Transpose)
Error_at_hidden_layer = np.dot(d_output, w_out.T)
print(Error_at_hidden_layer)

print("Step 9: Compute delta at hidden layer")
#d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
print(d_hiddenlayer)

print("Step 10: Update weight at both output and hidden layer")
w_out = w_out + np.dot(hiddenlayer_activations.T, d_output) * 0.1
wh = wh+ np.dot(x.T,d_hiddenlayer) * 0.1
print(w_out)
print(wh)

print("Step 11: Update biases at both output and hidden layer")
bh = bh + np.sum(d_hiddenlayer, axis=0) * 0.1
b_out = b_out + np.sum(d_output, axis=0)*0.1
print(bh)
print(b_out)

Step 1: Initialize weights and biases with random values
[[1 0 1 0]
 [1 0 1 1]
 [0 1 0 1]]
[[0.49 0.69 0.47]
 [0.38 0.85 0.98]
 [0.02 0.91 0.05]
 [0.93 0.31 0.07]]
[[0.69 0.86 0.94]
 [0.69 0.86 0.94]
 [0.69 0.86 0.94]]
[0.98 0.39 0.98]
[0.91 0.91 0.91]
Step 2 Calculate hidden layer input:
[[1.2  2.46 1.46]
 [2.13 2.77 1.53]
 [2.   2.02 1.99]]
Step 3: Perform non-linear transformation on hidden linear input
[[0.76852478 0.92128966 0.81153267]
 [0.89378501 0.94103299 0.82200631]
 [0.88079708 0.88288101 0.87974314]]
Step 4: Perform linear and non-linear transformation of hidden layer activation at output layer
[0.94362799 0.95066267 0.95164641]
Step 5: Calculate gradient of Error(E) at output layer
[ 0.05637201  0.04933733 -0.95164641]
Step 6: Compute slope at output and hidden layer
[0.20167393 0.20104913 0.2009616 ]
[[0.21643714 0.20364384 0.21296838]
 [0.20603822 0.20190388 0.21210668]
 [0.20715623 0.20697741 0.20724658]]
Step 7: Compute delta at output layer
[ 0.00113688  0.00099192 -