<a href="https://colab.research.google.com/github/gopal2812/mlblr/blob/master/nlpLet's_Code_Lecture2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# One hot encoding using Pytorch

In [2]:
import torch
torch.manual_seed(0)

In [47]:
corpus = [
    'he is a king',
    'she is a queen',
    'he is a man',
    'she is a woman',
    'queen is a woman',
    'king is a he', 
]

In [48]:
def tokenize_corpus(corpus):
    tokens = [x.split() for x in corpus]
    return tokens

tokenized_corpus = tokenize_corpus(corpus)

In [49]:
tokenized_corpus

[['he', 'is', 'a', 'king'],
 ['she', 'is', 'a', 'queen'],
 ['he', 'is', 'a', 'man'],
 ['she', 'is', 'a', 'woman'],
 ['queen', 'is', 'a', 'woman'],
 ['king', 'is', 'a', 'he']]

In [52]:
vocabulary = []
for sentence in tokenized_corpus:
    for token in sentence:
        if token not in vocabulary:
            vocabulary.append(token)

word2idx = {w: idx for (idx, w) in enumerate(vocabulary)}
idx2word = {idx: w for (idx, w) in enumerate(vocabulary)}

vocabulary_size = len(vocabulary)

In [53]:
vocabulary_size, vocabulary

(8, ['he', 'is', 'a', 'king', 'she', 'queen', 'man', 'woman'])

In [14]:
word2idx

{'a': 2,
 'berlin': 11,
 'capital': 10,
 'france': 14,
 'germany': 12,
 'he': 0,
 'is': 1,
 'king': 3,
 'man': 6,
 'paris': 13,
 'poland': 9,
 'queen': 5,
 'she': 4,
 'warsaw': 8,
 'woman': 7}

In [15]:
idx2word

{0: 'he',
 1: 'is',
 2: 'a',
 3: 'king',
 4: 'she',
 5: 'queen',
 6: 'man',
 7: 'woman',
 8: 'warsaw',
 9: 'poland',
 10: 'capital',
 11: 'berlin',
 12: 'germany',
 13: 'paris',
 14: 'france'}

In [16]:
window_size = 2
idx_pairs = []

# for each sentense
for sentense in tokenized_corpus:
    indices = [word2idx[word] for word in sentence]

indices, tokenized_corpus[-1]

([13, 1, 14, 10], ['paris', 'is', 'france', 'capital'])

In [17]:
# for each sentense
for sentense in tokenized_corpus:
    indices = [word2idx[word] for word in sentence]
    # for each word, treated as center word
    for center_word_pos in range(len(indices)):
        # for each window position
        for w in range(-window_size, window_size + 1):
            context_word_pos = center_word_pos + w
            if context_word_pos < 0 or context_word_pos >= len(indices) or center_word_pos == context_word_pos:
                continue
            context_word_idx = indices[context_word_pos]
            idx_pairs.append((indices[center_word_pos], context_word_idx))
        print(idx_pairs)
        pass

[(13, 1), (13, 14)]
[(13, 1), (13, 14), (1, 13), (1, 14), (1, 10)]
[(13, 1), (13, 14), (1, 13), (1, 14), (1, 10), (14, 13), (14, 1), (14, 10)]
[(13, 1), (13, 14), (1, 13), (1, 14), (1, 10), (14, 13), (14, 1), (14, 10), (10, 1), (10, 14)]
[(13, 1), (13, 14), (1, 13), (1, 14), (1, 10), (14, 13), (14, 1), (14, 10), (10, 1), (10, 14), (13, 1), (13, 14)]
[(13, 1), (13, 14), (1, 13), (1, 14), (1, 10), (14, 13), (14, 1), (14, 10), (10, 1), (10, 14), (13, 1), (13, 14), (1, 13), (1, 14), (1, 10)]
[(13, 1), (13, 14), (1, 13), (1, 14), (1, 10), (14, 13), (14, 1), (14, 10), (10, 1), (10, 14), (13, 1), (13, 14), (1, 13), (1, 14), (1, 10), (14, 13), (14, 1), (14, 10)]
[(13, 1), (13, 14), (1, 13), (1, 14), (1, 10), (14, 13), (14, 1), (14, 10), (10, 1), (10, 14), (13, 1), (13, 14), (1, 13), (1, 14), (1, 10), (14, 13), (14, 1), (14, 10), (10, 1), (10, 14)]
[(13, 1), (13, 14), (1, 13), (1, 14), (1, 10), (14, 13), (14, 1), (14, 10), (10, 1), (10, 14), (13, 1), (13, 14), (1, 13), (1, 14), (1, 10), (14, 13

In [19]:
import numpy as np
window_size = 2
idx_pairs = []
# for each sentence
for sentence in tokenized_corpus:
    indices = [word2idx[word] for word in sentence]
    # for each word, threated as center word
    for center_word_pos in range(len(indices)):
        # for each window position
        for w in range(-window_size, window_size + 1):
            context_word_pos = center_word_pos + w
            if context_word_pos < 0 or context_word_pos >= len(indices) or center_word_pos == context_word_pos:
                continue
            context_word_idx = indices[context_word_pos]
            idx_pairs.append((indices[center_word_pos], context_word_idx))

idx_pairs = np.array(idx_pairs) 

idx_pairs[:100]

array([[ 0,  1],
       [ 0,  2],
       [ 1,  0],
       [ 1,  2],
       [ 1,  3],
       [ 2,  0],
       [ 2,  1],
       [ 2,  3],
       [ 3,  1],
       [ 3,  2],
       [ 4,  1],
       [ 4,  2],
       [ 1,  4],
       [ 1,  2],
       [ 1,  5],
       [ 2,  4],
       [ 2,  1],
       [ 2,  5],
       [ 5,  1],
       [ 5,  2],
       [ 0,  1],
       [ 0,  2],
       [ 1,  0],
       [ 1,  2],
       [ 1,  6],
       [ 2,  0],
       [ 2,  1],
       [ 2,  6],
       [ 6,  1],
       [ 6,  2],
       [ 4,  1],
       [ 4,  2],
       [ 1,  4],
       [ 1,  2],
       [ 1,  7],
       [ 2,  4],
       [ 2,  1],
       [ 2,  7],
       [ 7,  1],
       [ 7,  2],
       [ 8,  1],
       [ 8,  9],
       [ 1,  8],
       [ 1,  9],
       [ 1, 10],
       [ 9,  8],
       [ 9,  1],
       [ 9, 10],
       [10,  1],
       [10,  9],
       [11,  1],
       [11, 12],
       [ 1, 11],
       [ 1, 12],
       [ 1, 10],
       [12, 11],
       [12,  1],
       [12, 10],
       [10,  1

In [20]:
![image](https://miro.medium.com/max/335/1*uYiqfNrUIzkdMrmkBWGMPw.png)

/bin/bash: -c: line 0: syntax error near unexpected token `https://miro.medium.com/max/335/1*uYiqfNrUIzkdMrmkBWGMPw.png'
/bin/bash: -c: line 0: `[image](https://miro.medium.com/max/335/1*uYiqfNrUIzkdMrmkBWGMPw.png)'


In [21]:
def get_input_layer(word_idx):
    x = torch.zeros(vocabulary_size).float()
    x[word_idx] = 1
    return x


In [22]:
get_input_layer(idx_pairs[1]), idx_pairs[1]

(tensor([1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0, 2]))

In [24]:
embedding_dims = 5
import torch
from torch.autograd import Variable
import numpy as np
import torch.functional as F
import torch.nn.functional as F

W1 = Variable(torch.randn(embedding_dims, vocabulary_size).float(), requires_grad=True)
W2 = Variable(torch.randn(vocabulary_size, embedding_dims).float(), requires_grad=True)
num_epochs = 101
learning_rate = 0.001

In [25]:
W1

tensor([[-1.1258, -1.1524, -0.2506, -0.4339,  0.8487,  0.6920, -0.3160, -2.1152,
          0.3223, -1.2633,  0.3500,  0.3081,  0.1198,  1.2377,  1.1168],
        [-0.2473, -1.3527, -1.6959,  0.5667,  0.7935,  0.5988, -1.5551, -0.3414,
          1.8530,  0.7502, -0.5855, -0.1734,  0.1835,  1.3894,  1.5863],
        [ 0.9463, -0.8437, -0.6136,  0.0316, -0.4927,  0.2484,  0.4397,  0.1124,
          0.6408,  0.4412, -0.1023,  0.7924, -0.2897,  0.0525,  0.5229],
        [ 2.3022, -1.4689, -1.5867, -0.6731,  0.8728,  1.0554,  0.1778, -0.2303,
         -0.3918,  0.5433, -0.3952, -0.4462,  0.7440,  1.5210,  2.3804],
        [-1.1256, -0.3170, -1.0925, -0.0852, -0.0933,  0.6871, -0.8383,  0.0185,
         -0.7504,  0.1854,  0.6211,  0.6382, -0.2460,  2.3025, -1.8817]],
       requires_grad=True)

In [26]:
idx_pairs[1]

array([0, 2])

In [27]:
x = Variable(get_input_layer(idx_pairs[1][0])).float()
y_true = Variable(torch.from_numpy(np.array([idx_pairs[1][1]])).long())
x, y_true

(tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([2]))

In [28]:
num_epochs = 1001
for epo in range(num_epochs):
    loss_val = 0
    for data, target in idx_pairs:
        x = Variable(get_input_layer(data)).float()
        y_true = Variable(torch.from_numpy(np.array([target])).long())

        z1 = torch.matmul(W1, x)
        z2 = torch.matmul(W2, z1)
    
        log_softmax = F.log_softmax(z2, dim=0)

        loss = F.nll_loss(log_softmax.view(1,-1), y_true)
        loss_val += loss.data
        loss.backward()
        W1.data -= learning_rate * W1.grad.data
        W2.data -= learning_rate * W2.grad.data

        W1.grad.data.zero_()
        W2.grad.data.zero_()
    if epo % 10 == 0:    
        print(f'Loss at epo {epo}: {loss_val/len(idx_pairs)}')

Loss at epo 0: 4.716522216796875
Loss at epo 10: 4.006479740142822
Loss at epo 20: 3.6423211097717285
Loss at epo 30: 3.385183811187744
Loss at epo 40: 3.186298370361328
Loss at epo 50: 3.028099775314331
Loss at epo 60: 2.900906562805176
Loss at epo 70: 2.7977652549743652
Loss at epo 80: 2.713106155395508
Loss at epo 90: 2.6424407958984375
Loss at epo 100: 2.582277774810791
Loss at epo 110: 2.530010223388672
Loss at epo 120: 2.48374080657959
Loss at epo 130: 2.4421167373657227
Loss at epo 140: 2.404170274734497
Loss at epo 150: 2.36920428276062
Loss at epo 160: 2.336711883544922
Loss at epo 170: 2.30631422996521
Loss at epo 180: 2.2777247428894043
Loss at epo 190: 2.250720977783203
Loss at epo 200: 2.225130319595337
Loss at epo 210: 2.2008142471313477
Loss at epo 220: 2.1776585578918457
Loss at epo 230: 2.1555728912353516
Loss at epo 240: 2.1344823837280273
Loss at epo 250: 2.1143248081207275
Loss at epo 260: 2.095048189163208
Loss at epo 270: 2.0766079425811768
Loss at epo 280: 2.0589

In [29]:
x = Variable(get_input_layer(idx_pairs[4][0])).float()
z1 = torch.matmul(W1, x)
z2 = torch.matmul(W2, z1)
log_softmax = F.log_softmax(z2, dim=0)
log_softmax

tensor([-2.7520, -4.1288, -1.9288, -2.8932, -2.4999, -3.0845, -2.5590, -3.0506,
        -2.2745, -3.3338, -2.2651, -2.8315, -3.3817, -2.3201, -3.4016],
       grad_fn=<LogSoftmaxBackward>)

In [30]:
y_true = Variable(torch.from_numpy(np.array([idx_pairs[4][1]])).long())
y_true

tensor([3])

In [31]:
def text_to_onehot(text: str, corpus: str):
    # Read input file
    vocab = []
    with open(corpus, encoding="utf8") as f:
        passage = f.read()
        sentences = passage.lower().replace(".","").split('\n')
        for sentence in sentences:
            for word in sentence.split():
                if word not in vocab:
                    vocab.append(word)
    print(f'No. of words in our vocabulary: {len(vocab)}')
    print(vocab, '\n')

    # split the provided text into words
    txt = text.split()

    # Extract ranks out of word list
    rank_list = [rank for rank, _ in enumerate(vocab)]

    # Encode rank as one-hot vectors
    vocab_dict = {}
    text_vec = torch.zeros(len(txt), len(vocab)) # length of vocab is embedding size
    vocab_vec = torch.zeros(len(vocab), len(vocab))
    vocab_vec[torch.arange(len(vocab)), rank_list] = 1
    
    # create dict for mapping word to one-hot vector
    for index, word in enumerate(vocab):
            vocab_dict[word] = vocab_vec[index]
    
    # for each word of text in vocab assign its one-hot value
    for index, word in enumerate(txt):
        if word in vocab:
            text_vec[index] = vocab_dict[word]
    print(f'One hot vector of your text based on corpus:\n {text_vec}')

In [32]:
text_to_onehot('man eats biscuits and scares dog','corpus.txt')

FileNotFoundError: ignored

**Words in our text which are not in corpus gets all zero one-hot vector. Thats OOV**.

# BOW Model using sklearn

In [33]:
processed_docs = []
with open('corpus.txt', encoding="utf8") as f:
    passage = f.read()
processed_docs = passage.lower().replace(".","").split('\n')
processed_docs

FileNotFoundError: ignored

In [46]:
from sklearn.feature_extraction.text import CountVectorizer

#look at the documents list
print("Our corpus: ", processed_docs)

count_vect = CountVectorizer()
#Build a BOW representation for the corpus
bow_rep = count_vect.fit_transform(processed_docs)

#Look at the vocabulary mapping
print("Our vocabulary: ", count_vect.vocabulary_)

#see the BOW rep for first 2 documents
print("BoW representation for 'dog bites man': ", bow_rep[0].toarray())
print("BoW representation for 'man bites dog: ", bow_rep[1].toarray())

#Get the representation using this vocabulary, for a new text
temp = count_vect.transform(["dog and dog are friends"])
print("Bow representation:", temp.toarray())

Our corpus:  []


ValueError: ignored

Here we are considering the frequency of words into account. However, sometimes, we don't care about frequency much, but only want to know whether a word appeared in a text or not. That is, each document is represented as a vector of 0s and 1s. We use the option binary=True in CountVectorizer for this purpose. This results in a different representation for the same sentence.

# Bag of N-grams

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer


#Ngram vectorization example with count vectorizer and uni, bi, trigrams
count_vect = CountVectorizer(ngram_range=(1,3))

#Build a BOW representation for the corpus
bow_rep = count_vect.fit_transform(processed_docs)

#Look at the vocabulary mapping
print("Our vocabulary: ", count_vect.vocabulary_)

#see the BOW rep for first 2 documents
print("BoW representation for 'dog bites man': ", bow_rep[0].toarray())
print("BoW representation for 'man bites dog: ", bow_rep[1].toarray())

#Get the representation using this vocabulary, for a new text
temp = count_vect.transform(["dog and dog are friends"])

print("Bow representation:", temp.toarray())

Note that the number of features (and hence the size of the feature vector) increased a lot for the same data, compared to the ther single word based representations!!

# TF-IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
bow_rep_tfidf = tfidf.fit_transform(processed_docs)

# IDF for all words in the vocabulary
print("IDF for all words in the vocabulary",tfidf.idf_)
print("-"*10)

# All words in the vocabulary.
print("All words in the vocabulary",tfidf.get_feature_names())
print("-"*10)

# TFIDF representation for all documents in our corpus 
print("TFIDF representation for all documents in our corpus\n",bow_rep_tfidf.toarray()) 
print("-"*10)

temp = tfidf.transform(["dog and man are friends"])
print("Tfidf representation:\n", temp.toarray())

# Pre-trained word2vec model

Google News Dataset

In [6]:
!wget -P /tmp/input/ -c "https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz"

--2020-10-29 17:00:19--  https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.217.86.6
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.217.86.6|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1647046227 (1.5G) [application/x-gzip]
Saving to: ‘/tmp/input/GoogleNews-vectors-negative300.bin.gz’

GoogleNews-vectors- 100%[===================>]   1.53G  87.8MB/s    in 19s     

2020-10-29 17:00:38 (84.0 MB/s) - ‘/tmp/input/GoogleNews-vectors-negative300.bin.gz’ saved [1647046227/1647046227]



In [34]:
import warnings # This module ignores the various types of warnings generated
warnings.filterwarnings("ignore") 

import os # This module provides a way of using operating system dependent functionality

import psutil # This module helps in retrieving information on running processes and system resource utilization
process = psutil.Process(os.getpid())
from psutil import virtual_memory
mem = virtual_memory()

import time # This module is used to calculate the time

In [8]:
from gensim.models import Word2Vec, KeyedVectors
pretrainedpath = '/tmp/input/GoogleNews-vectors-negative300.bin.gz'

# Load W2V model. This will take some time, but it is a one time effort! 
pre = process.memory_info().rss
print("Memory used in GB before Loading the Model: %0.2f"%float(pre/(10**9))) #Check memory usage before loading the model
print('-'*10)

start_time = time.time() # Start the timer
ttl = mem.total # Total memory available

w2v_model = KeyedVectors.load_word2vec_format(pretrainedpath, binary=True) # load the model
print("%0.2f seconds taken to load"%float(time.time() - start_time)) # Calculate the total time elapsed since starting the timer
print('-'*10)

print('Finished loading Word2Vec')
print('-'*10)

post = process.memory_info().rss
print("Memory used in GB after Loading the Model: {:.2f}".format(float(post/(10**9)))) # Calculate the memory used after loading the model
print('-'*10)

print("Percentage increase in memory usage: {:.2f}% ".format(float((post/pre)*100))) # Percentage increase in memory after loading the model
print('-'*10)

print("Numver of words in vocablulary: ",len(w2v_model.vocab)) # Number of words in the vocabulary.

Memory used in GB before Loading the Model: 0.29
----------
119.99 seconds taken to load
----------
Finished loading Word2Vec
----------
Memory used in GB after Loading the Model: 5.14
----------
Percentage increase in memory usage: 1770.43% 
----------
Numver of words in vocablulary:  3000000


In [35]:
#Let us examine the model by knowing what the most similar words are, for a given word!
w2v_model.most_similar('beautiful')

[('gorgeous', 0.8353004455566406),
 ('lovely', 0.810693621635437),
 ('stunningly_beautiful', 0.7329413890838623),
 ('breathtakingly_beautiful', 0.7231341004371643),
 ('wonderful', 0.6854087114334106),
 ('fabulous', 0.6700063943862915),
 ('loveliest', 0.6612576246261597),
 ('prettiest', 0.6595001816749573),
 ('beatiful', 0.6593326330184937),
 ('magnificent', 0.6591402292251587)]

In [ ]:
# What if I am looking for a word that is not in this vocabulary?
w2v_model['kaunhotum?']

# Train our Embedding on WikiCorpus using GenSim

In [ ]:
from gensim.models import Word2Vec
import warnings
warnings.filterwarnings('ignore')

In [ ]:
# define training data
# Genism word2vec requires that a format of ‘list of lists’ be provided for training where every document contained in a list.
# Every list contains lists of tokens of that document.
corpus = [["dog","eats","biscuits"],["man", "eats","biscuits"],['dog','bites','man'], ["man", "bites" ,"dog"]]

#Training the model
model_cbow = Word2Vec(corpus, min_count=1,sg=0) # using CBOW Architecture for trainnig
model_skipgram = Word2Vec(corpus, min_count=1,sg=1)# using skipGram Architecture for training

### Continuous Bag of Words (CBOW)

In [ ]:
#Summarize the loaded model
print(model_cbow)

#Summarize vocabulary
words = list(model_cbow.wv.vocab)
print(words)

#Acess vector for one word
print(model_cbow['dog'])

In [ ]:
#Compute similarity 
print("Similarity between eats and bites:",model_cbow.similarity('eats', 'bites'))
print("Similarity between eats and man:",model_cbow.similarity('eats', 'man'))

From the above similarity scores we can conclude that eats is more similar to bites than man.

### SkipGram

In [ ]:
#Summarize the loaded model
print(model_skipgram)

#Summarize vocabulary
words = list(model_skipgram.wv.vocab)
print(words)

#Acess vector for one word
print(model_skipgram['dog'])

In [ ]:
# Compute similarity 
print("Similarity between eats and bites:",model_skipgram.similarity('eats', 'bites'))
print("Similarity between eats and man:",model_skipgram.similarity('eats', 'man'))

### Training Your Embedding on Wiki Corpus

In [38]:
!mkdir -p data/en/
!wget -P data/en/ https://dumps.wikimedia.org/enwiki/20201001/enwiki-20201001-pages-articles-multistream14.xml-p13159683p14324602.bz2

--2020-10-29 17:22:00--  https://dumps.wikimedia.org/enwiki/20201001/enwiki-20201001-pages-articles-multistream14.xml-p13159683p14324602.bz2
Resolving dumps.wikimedia.org (dumps.wikimedia.org)... 208.80.154.7, 2620:0:861:1:208:80:154:7
Connecting to dumps.wikimedia.org (dumps.wikimedia.org)|208.80.154.7|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 290813119 (277M) [application/octet-stream]
Saving to: ‘data/en/enwiki-20201001-pages-articles-multistream14.xml-p13159683p14324602.bz2’

enwiki-20201001-pag 100%[===================>] 277.34M  4.76MB/s    in 57s     

2020-10-29 17:22:57 (4.86 MB/s) - ‘data/en/enwiki-20201001-pages-articles-multistream14.xml-p13159683p14324602.bz2’ saved [290813119/290813119]



In [39]:
from gensim.corpora.wikicorpus import WikiCorpus
from gensim.models.word2vec import Word2Vec
from gensim.models.fasttext import FastText
import time

In [40]:
#Preparing the Training data
wiki = WikiCorpus('data/en/enwiki-20201001-pages-articles-multistream14.xml-p13159683p14324602.bz2', 
                  lemmatize=False, dictionary={})
sentences = list(wiki.get_texts())

#### Hyperparameters
sg - Selecting the training algorithm: 1 for skip-gram else its 0 for CBOW. Default is CBOW.

min_count- Ignores all words with total frequency lower than this.

### CBOW


In [41]:
start = time.time()
word2vec_cbow = Word2Vec(sentences,min_count=10, sg=0)
end = time.time()

print("CBOW Model Training Complete.\nTime taken for training is:{:.2f} hrs ".format((end-start)/3600.0))

CBOW Model Training Complete.
Time taken for training is:0.10 hrs 


In [42]:
#Summarize the loaded model
print(word2vec_cbow)
print("-"*30)

#Summarize vocabulary
words = list(word2vec_cbow.wv.vocab)
print(words)
print("-"*30)

#Acess vector for one word
print(word2vec_cbow['film'])
print("-"*30)

#Compute similarity 
print("Similarity between film and drama:",word2vec_cbow.similarity('film', 'drama'))
print("Similarity between film and dog:",word2vec_cbow.similarity('film', 'dog'))
print("-"*30)

Word2Vec(vocab=110266, size=100, alpha=0.025)
------------------------------
['the', 'roses', 'registered', 'as', 'is', 'brisbane', 'racing', 'club', 'group', 'thoroughbred', 'horse', 'race', 'for', 'three', 'year', 'old', 'filles', 'run', 'under', 'set', 'weights', 'conditions', 'over', 'distance', 'of', 'metres', 'at', 'racecourse', 'australia', 'during', 'queensland', 'winter', 'carnival', 'total', 'prizemoney', 'history', 'it', 'currently', 'main', 'lead', 'up', 'oaks', 'most', 'notable', 'winner', 'ethereal', 'who', 'went', 'on', 'to', 'win', 'that', 'melbourne', 'cup', 'in', 'winning', 'new', 'record', 'metre', 'two', 'fillies', 'have', 'won', 'double', 'and', 'scarlett', 'lady', 'trainers', 'this', 'twice', 'roger', 'james', 'graeme', 'rogerson', 'jockeys', 'greg', 'childs', 'darren', 'name', 'onwards', 'grade', 'listed', 'venue', 'eagle', 'farm', 'winners', 'vanna', 'girl', 'bohemian', 'lily', 'arabian', 'gold', 'dear', 'demi', 'invest', 'awesome', 'planet', 'heavenly', 'glow',

In [43]:
# save model
from gensim.models import Word2Vec, KeyedVectors   
word2vec_cbow.wv.save_word2vec_format('word2vec_cbow.bin', binary=True)

# # load model
# new_modelword2vec_cbow = Word2Vec.load('word2vec_cbow.bin')
# print(word2vec_cbow)

### SkipGram

In [44]:
start = time.time()
word2vec_skipgram = Word2Vec(sentences,min_count=10, sg=1)
end = time.time()

print("SkipGram Model Training Complete\nTime taken for training is:{:.2f} hrs ".format((end-start)/3600.0))

SkipGram Model Training Complete
Time taken for training is:0.33 hrs 


In [45]:
#Summarize the loaded model
print(word2vec_skipgram)
print("-"*30)

#Summarize vocabulary
words = list(word2vec_skipgram.wv.vocab)
print(words)
print("-"*30)

#Acess vector for one word
print(word2vec_skipgram['film'])
print("-"*30)

#Compute similarity 
print("Similarity between film and drama:", word2vec_skipgram.similarity('film', 'drama'))
print("Similarity between film and dog:",word2vec_skipgram.similarity('film', 'dog'))
print("-"*30)

Word2Vec(vocab=110266, size=100, alpha=0.025)
------------------------------
['the', 'roses', 'registered', 'as', 'is', 'brisbane', 'racing', 'club', 'group', 'thoroughbred', 'horse', 'race', 'for', 'three', 'year', 'old', 'filles', 'run', 'under', 'set', 'weights', 'conditions', 'over', 'distance', 'of', 'metres', 'at', 'racecourse', 'australia', 'during', 'queensland', 'winter', 'carnival', 'total', 'prizemoney', 'history', 'it', 'currently', 'main', 'lead', 'up', 'oaks', 'most', 'notable', 'winner', 'ethereal', 'who', 'went', 'on', 'to', 'win', 'that', 'melbourne', 'cup', 'in', 'winning', 'new', 'record', 'metre', 'two', 'fillies', 'have', 'won', 'double', 'and', 'scarlett', 'lady', 'trainers', 'this', 'twice', 'roger', 'james', 'graeme', 'rogerson', 'jockeys', 'greg', 'childs', 'darren', 'name', 'onwards', 'grade', 'listed', 'venue', 'eagle', 'farm', 'winners', 'vanna', 'girl', 'bohemian', 'lily', 'arabian', 'gold', 'dear', 'demi', 'invest', 'awesome', 'planet', 'heavenly', 'glow',

**Skipgram took more time to train than BOW, any guess??**